# CSV Import Tool Configuration

spring:
  application:
    name: csv-import-tool
  
  # 禁用自动配置的数据源（我们使用动态数据源）
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibariAutoConfiguration

# 日志配置
logging:
  level:
    com.example.csvimport: INFO
    org.springframework.jdbc: WARN
    com.zaxxer.hikari: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/csv-import.log
    max-size: 100MB
    max-history: 30

# 应用配置
csv-import:
  # 默认配置
  default:
    batch-size: 1000
    sample-size: 1000
    connection-timeout: 30000
    max-pool-size: 20
    min-idle: 5
  
  # 性能配置
  performance:
    # 是否启用批量重写（MySQL性能优化）
    enable-batch-rewrite: true
    # 是否启用预编译语句缓存
    enable-prep-stmt-cache: true
    # 预编译语句缓存大小
    prep-stmt-cache-size: 250
    # 预编译语句SQL限制
    prep-stmt-cache-sql-limit: 2048