# Spring Boot 应用配置
spring:
  application:
    name: aq2-post-task
  
  # 数据源配置（示例配置，实际使用时根据需要调整）
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 注意：这里的配置是示例，实际的数据库连接信息将从请求中获取
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: password
    
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  # Jackson配置
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# 日志配置
logging:
  level:
    com.example.aq2: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/aq2-post-task.log
    max-size: 10MB
    max-history: 30

# 应用自定义配置
app:
  name: AQ2.0 Post Task API
  version: 1.0.0
  description: 处理复杂查询请求的Spring Boot API
  
  # FTP配置
  ftp:
    connection-timeout: 30000
    data-timeout: 60000
    
  # 数据库配置
  database:
    connection-timeout: 5000
    validation-timeout: 5000