version: '3.8'

services:
  # Master 服务
  seaweedfs-master:
    image: chrislusf/seaweedfs:latest
    container_name: seaweedfs-master
    ports:
      - "9333:9333"
      - "19333:19333"
    command: "master -ip=seaweedfs-master -port=9333 -mdir=/data"
    volumes:
      - seaweed-master-data:/data
    networks:
      - seaweedfs-network

  # Volume 服务
  seaweedfs-volume:
    image: chrislusf/seaweedfs:latest
    container_name: seaweedfs-volume
    ports:
      - "8080:8080"
      - "18080:18080"
    command: "volume -mserver=seaweedfs-master:9333 -port=8080 -ip=seaweedfs-volume -dir=/data"
    volumes:
      - seaweed-volume-data:/data
    depends_on:
      - seaweedfs-master
    networks:
      - seaweedfs-network

  # Filer 服务
  seaweedfs-filer:
    image: chrislusf/seaweedfs:latest
    container_name: seaweedfs-filer
    ports:
      - "8888:8888"
      - "18888:18888"
    command: "filer -master=seaweedfs-master:9333"
    depends_on:
      - seaweedfs-master
      - seaweedfs-volume
    networks:
      - seaweedfs-network

  # S3 Gateway 服务 (关键!)
  seaweedfs-s3:
    image: chrislusf/seaweedfs:latest
    container_name: seaweedfs-s3
    ports:
      - "8333:8333"  # S3 API 端口
    command: "s3 -filer=seaweedfs-filer:8888 -port=8333"
    depends_on:
      - seaweedfs-filer
    networks:
      - seaweedfs-network
    environment:
      - WEED_S3_DEFAULT_USER_ID=nvx1
      - WEED_S3_DEFAULT_ACCESS_KEY=nvx1  
      - WEED_S3_DEFAULT_SECRET_KEY=nvx1
  
  # 初始化bucket
  seaweed-init:
    image: amazon/aws-cli:latest
    container_name: seaweed-init
    depends_on:
      - seaweedfs-s3
    environment:
      - AWS_ACCESS_KEY_ID=nvx1
      - AWS_SECRET_ACCESS_KEY=nvx1
     # - AWS_DEFAULT_REGION=us-east-1
    command: >
      sh -c "
        sleep 1000 &&
        aws --endpoint-url=http://seaweedfs-s3:8333 s3 mb s3://test &&
        aws --endpoint-url=http://seaweedfs-s3:8333 s3 mb s3://uploads &&
        aws --endpoint-url=http://seaweedfs-s3:8333 s3 mb s3://backups &&
        echo 'Buckets created successfully'
      "
    networks:
      - seaweedfs-network
    restart: "no"  # 只运行一次

volumes:
  seaweed-master-data:
  seaweed-volume-data:

networks:
  seaweedfs-network:
    driver: bridge
